name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3x #Replace with your desired py version

      - name: Install dependencies
        run: pip install -r requirements.txt #if you have requiremts.txtfile

      -name: Run tests
       run: pyhton -m unittest discover

